import { useEffect, useMemo, useState } from 'react'
import { LANGUAGE_KEY } from '../lib/defaults'
import type { Language } from '../lib/types'

const LANGUAGE_CHANGE_EVENT = 'budget-language-change'

const zh: Record<string, string> = {
  'nav.home': '首頁',
  'nav.overview': '總覽',
  'nav.expenses': '支出',
  'nav.giftcards': '禮品卡',
  'nav.cards': '信用卡',
  'nav.benefits': '權益追蹤',
  'nav.analytics': '分析',
  'nav.settings': '設定',
  'app.subtitle': '個人支出記帳',
  'app.addExpense': '新增支出',
  'app.toggleTheme': '切換深淺色',
  'app.openNavigation': '開啟選單',
  'app.tipTitle': '小提示',
  'app.tipText': '點 + 快速新增一筆支出。',

  'settings.spreadsheet': '試算表',
  'settings.spreadsheetDescription': 'Google Sheets 資料庫連線。',
  'settings.connectedSheet': '目前連接的試算表',
  'settings.openSheets': '在 Google Sheets 開啟 ↗',
  'settings.changeSpreadsheet': '更換試算表',
  'settings.account': '帳號',
  'settings.accountDescription': '已使用 Google 登入。',
  'settings.profileUnavailable': '無法取得帳號 email',
  'settings.signOut': '登出',
  'settings.appearance': '外觀',
  'settings.appearanceDescription': '選擇配色、深淺色與語言。設定會儲存在這台裝置。',
  'settings.language': '語言',
  'settings.english': 'English',
  'settings.chinese': '中文',
  'settings.brightness': '深淺色',
  'settings.light': '淺色',
  'settings.dark': '深色',
  'settings.system': '跟隨系統',
  'settings.dataCounts': '資料數量',
  'settings.total': '總筆數',
  'settings.oldest': '最早',
  'settings.newest': '最新',

  'theme.coral.description': '原本溫暖活潑的配色',
  'theme.chamomile.description': '柔和洋甘菊、奶油與杏桃色',
  'theme.sea.description': '平靜的海玻璃與海藍色',
  'theme.milk-tea.description': '溫暖焦糖與奶茶米色',
  'theme.lavender.description': '柔和薰衣草與莓果色',
  'theme.matcha.description': '清新的抹茶綠與鼠尾草綠',

  'expense.addTitle': '新增支出',
  'expense.editTitle': '編輯支出',
  'expense.savedToSheet': '直接儲存到你的 Google Sheet',
  'expense.date': '日期',
  'expense.today': '今天',
  'expense.yesterday': '昨天',
  'expense.twoDaysAgo': '前天',
  'expense.description': '描述',
  'expense.descriptionPlaceholder': '超市、房租、咖啡...',
  'expense.addNote': '+ 新增備註',
  'expense.removeNote': '移除備註',
  'expense.notePlaceholder': '備註：信用卡回饋、分帳晚餐...',
  'expense.amount': '金額',
  'expense.costPaid': '支付成本',
  'expense.category': '分類',
  'expense.categoryPlaceholder': '選擇或輸入分類',
  'expense.paymentMethod': '付款方式',
  'expense.card': '信用卡',
  'expense.giftcard': '禮品卡',
  'expense.cash': '現金',
  'expense.splitPayments': '拆分成多種付款方式',
  'expense.tags': '標籤',
  'expense.tagPlaceholder': '旅行、房子、專案...',
  'expense.tagAnotherPlaceholder': '再新增一個標籤...',
  'expense.addTag': '新增',
  'expense.tagHelp': '選擇既有標籤或輸入新的標籤。逗號可一次新增多個。',
  'expense.cancel': '取消',
  'expense.saveChanges': '儲存變更',
  'expense.addExpense': '新增支出',
  'expense.saving': '儲存中...',
  'expense.updated': '支出已更新',
  'expense.added': '支出已新增',
  'expense.amountRequired': '請輸入金額。',
  'expense.paymentRequired': '請選擇付款方式。',
  'expense.descriptionRequired': '請輸入描述。',

  'card.addTitle': '新增信用卡',
  'card.editTitle': '編輯信用卡',
  'card.description': '儲存信用卡設定到 Google Sheets 的 Cards 分頁。',
  'card.name': '名稱',
  'card.issuer': '發卡銀行',
  'card.last4': '末四碼',
  'card.annualFee': '年費',
  'card.openDate': '開卡日期',
  'card.active': '啟用',
  'card.note': '備註',
  'card.notePlaceholder': '權益、提醒事項...',
  'card.subTracking': '開卡禮追蹤',
  'card.optional': '選填',
  'card.targetSpend': '消費門檻',
  'card.period': '期間（月）',
  'card.bonus': '開卡禮',
  'card.deadline': '截止日',
  'card.subHint': '填寫上方開卡日期、消費門檻與期間即可啟用開卡禮追蹤。',
  'card.nameRequired': '請輸入信用卡名稱。',
  'card.addCard': '新增信用卡',
  'card.cardAdded': '信用卡已新增',
  'card.cardUpdated': '信用卡已更新',
  'card.saveCardError': '無法儲存信用卡',
  'card.loadError': '無法載入信用卡',
  'card.setupTitle': '設定試算表中的 Cards 分頁',
  'card.setupDescription': '建立包含 Name、Issuer、Product、Last4、Active、Note、Annual Fee、SUB Required、SUB Start、SUB Deadline、SUB Bonus 欄位的 Cards 分頁。',
  'card.creating': '建立中...',
  'card.createTab': '建立 Cards 分頁',
  'card.cardsOnList': '卡片數',
  'card.subOpen': '開卡禮進行中',
  'card.annualFees': '年費',
  'card.searchPlaceholder': '依名稱、發卡銀行、末四碼、備註搜尋...',
  'card.inactive': '停用',
  'card.showInactive': '顯示停用',
  'card.cardsView': '卡片',
  'card.newCard': '新卡',
  'card.noActive': '沒有啟用中的信用卡',
  'card.noCards': '尚無信用卡',
  'card.noSearchMatches': '找不到符合',
  'card.noActiveHelp': '所有信用卡都標示為停用，開啟「顯示停用」即可查看。',
  'card.noCardsHelp': '在這裡新增信用卡，之後新增支出時會優先出現在付款方式選單。',
  'card.allTime': '全部期間',
  'card.status': '狀態',

  'benefits.title': '權益追蹤',
  'benefits.description': '依產品追蹤權益，再查看每張啟用中的卡片。',
  'benefits.add': '新增權益',
  'benefits.addTitle': '新增權益',
  'benefits.editTitle': '編輯權益',
  'benefits.dialogDescription': '儲存信用卡權益模板到 Google Sheets 的 CardBenefits 分頁。',
  'benefits.empty': '尚無啟用中的權益可追蹤。',
  'benefits.setupTitle': '建立 CardBenefits 分頁即可在這裡追蹤信用卡權益。',
  'benefits.setupDescription': '欄位：Product、Benefit、Amount、Period、Category、Merchant/Tag、Start Date、End Date、Active。',
  'benefits.tracked': '追蹤中',
  'benefits.usedPeriod': '已使用',
  'benefits.leftPeriod': '剩餘',
  'benefits.searchCards': '搜尋卡片...',
  'benefits.benefitView': '權益檢視',
  'benefits.cardView': '卡片檢視',
  'benefits.noMatches': '沒有符合的卡片。',
  'benefits.leftShort': '剩餘',
  'benefits.usedButton': '已用',
  'benefits.done': '完成',
  'benefits.cardSingular': '張卡',
  'benefits.cardsPlural': '張卡',
  'benefits.creditSingular': '筆 credit',
  'benefits.creditsPlural': '筆 credit',
  'benefits.certificateSingular': '張憑證',
  'benefits.certificatePlural': '張憑證',
  'benefits.certificates': '憑證張數',
  'benefits.matchSingular': '筆符合',
  'benefits.matchesPlural': '筆符合',
  'benefits.productTemplate': '產品模板',
  'benefits.selectProduct': '選擇產品',
  'benefits.name': '權益名稱',
  'benefits.amount': '金額',
  'benefits.period': '週期',
  'benefits.period.monthly': '每月',
  'benefits.period.quarterly': '每季',
  'benefits.period.semiannual': '每半年',
  'benefits.period.annual': '每年',
  'benefits.anyCategory': '不限分類',
  'benefits.matcher': '商家／標籤',
  'benefits.startDate': '開始日期',
  'benefits.endDate': '結束日期',
  'benefits.dateExact': '指定日期',
  'benefits.dateAnnual': '每年',
  'benefits.productRequired': '請選擇產品。',
  'benefits.nameRequired': '請輸入權益名稱。',
  'benefits.amountRequired': '權益金額必須大於 0。',
  'benefits.updated': '權益已更新',
  'benefits.added': '權益已新增',
  'benefits.updateError': '無法更新權益',
  'benefits.addError': '無法新增權益',
  'benefits.deleteTitle': '刪除這個權益？',
  'benefits.deleteDescription': '這會清除 CardBenefits 的權益列。符合的支出與手動 credit 紀錄不會被刪除。',
  'benefits.actionsFor': '開啟權益選單',
  'benefits.editCreditTitle': '編輯權益 credit',
  'benefits.markCreditTitle': '標記權益 credit',
  'benefits.saveCredit': '儲存 credit',
  'benefits.creditRequired': '請輸入日期與金額。',
  'benefits.creditUpdated': '權益 credit 已更新',
  'benefits.creditAdded': '權益 credit 已新增',
  'benefits.creditSaveError': '無法儲存權益 credit',
  'benefits.status': '狀態',
  'benefits.received': '已收到',
  'benefits.pending': '待入帳',
  'benefits.creditNotePlaceholder': '預訂、statement credit、確認資訊...',

  'common.clear': '清除',
  'common.close': '關閉',
  'common.filters': '篩選',
  'common.showResults': '顯示結果',
  'common.tryAgain': '再試一次',
  'common.previous': '上一頁',
  'common.next': '下一頁',
  'common.edit': '編輯',
  'common.delete': '刪除',
  'common.copy': '複製',
  'common.return': '退貨',
  'common.select': '選取',
  'common.selected': '已選取',
  'common.search': '搜尋',
  'common.noMatches': '沒有符合結果',

  'expenses.searchPlaceholder': '搜尋支出...',
  'expenses.searchDescription': '搜尋描述...',
  'expenses.datePreset': '日期範圍',
  'expenses.thisMonth': '本月',
  'expenses.lastMonth': '上月',
  'expenses.thisYear': '今年',
  'expenses.all': '全部',
  'expenses.custom': '自訂',
  'expenses.filterTitle': '篩選',
  'expenses.filterDescription': '縮小支出範圍，不讓手機畫面太擁擠。',
  'expenses.cardView': '卡片檢視',
  'expenses.listView': '列表檢視',
  'expenses.viewMode': '支出檢視',
  'expenses.openMenu': '開啟支出選單',
  'expenses.openSheet': '在 Google Sheets 開啟',
  'expenses.showing': '顯示',
  'expenses.of': '共',
  'expenses.total': '總計',
  'expenses.noDescription': '無描述',
  'expenses.unknown': '未知',
  'expenses.empty': '🌱 還沒有資料，新增第一筆支出吧！',
  'expenses.actions': '操作',
  'expenses.deleted': '支出已刪除',
  'expenses.undo': '復原',
  'expenses.restoreError': '無法復原支出',
  'expenses.deleteError': '無法刪除支出',

  'batch.title': '批次編輯支出',
  'batch.description': '套用變更到選取的支出。',
  'batch.keepCurrent': '— 保持目前值 —',
  'batch.applyPayment': '套用付款方式',
  'batch.applyDate': '套用日期',
  'batch.applyTags': '套用標籤',
  'batch.chooseField': '請至少選擇一個欄位更新。',
  'batch.updatedZero': '已更新 0 筆支出',
  'batch.updateError': '無法更新支出',
  'batch.tagPlaceholder': '旅行、專案、家庭...',
  'batch.tagHelp': '這會取代所選支出的標籤。多個標籤請用逗號分隔。',
  'batch.noCategoryMatches': '沒有符合結果。繼續輸入可新增分類。',

  'filters.categories': '分類',
  'filters.payments': '付款方式',
  'filters.tags': '標籤',
  'filters.noPayment': '無付款方式',
  'filters.selectAllVisible': '選取所有顯示的支出',
  'filters.nowChooseEnd': '現在選擇結束日期',
  'filters.chooseRange': '選擇開始與結束日期',
  'filters.selectEnd': '選擇結束日',
  'filters.selectRange': '選擇日期範圍',
  'filters.customPrefix': '自訂',

  'return.addTitle': '新增退貨',
  'return.editTitle': '編輯退貨',
  'return.fullRefund': '全額退款',
  'return.fullRefundHint': '使用原購買金額',
  'return.date': '退貨日期',
  'return.amount': '退款金額',
  'return.description': '描述',
  'return.descriptionPlaceholder': 'Return: 購買描述（日期）',
  'return.category': '分類',
  'return.refundTo': '退款到',
  'return.saveReturn': '儲存退貨',
  'return.addReturn': '新增退貨',
  'return.amountRequired': '請輸入退款金額。',
  'return.tooMuch': '退款金額超過原購買金額。',
  'return.saveError': '無法儲存退貨',
  'return.updated': '退貨已更新',
  'return.added': '退貨已新增',
  'return.newGiftcard': '新的禮品卡／店家點數',
  'return.originalGiftcard': '原本的禮品卡',
  'return.newGiftcardName': '新禮品卡名稱',
  'return.newGiftcardHint': '建立一筆禮品卡資料，付款方式維持原本的付款方式。',
  'return.useOriginalGiftcard': '使用原本禮品卡',

  'overview.topCategories': '本月主要分類',
  'overview.recentExpenses': '最近支出',
  'overview.quickAdd': '快速新增',
  'overview.delta': '與上月相比',
  'overview.transactions': '交易筆數',

  'analytics.byCategory': '依分類',
  'analytics.byTag': '依標籤',
  'analytics.byPayment': '依付款',
  'analytics.monthlyTrend': '月趨勢',
  'analytics.yearCompare': '年度比較',
  'analytics.categoryTitle': '依分類支出',
  'analytics.categoryDescription': '點選分類聚焦，再查看符合的支出。',
  'analytics.tagTitle': '依標籤支出',
  'analytics.tagDescription': '用標籤追蹤旅行、專案、人或任何彈性用途。',
  'analytics.paymentTitle': '依付款方式支出',
  'analytics.paymentDescription': '查看哪些卡片或帳戶承擔最多支出。',
  'analytics.trendDescription': '用柔和的趨勢線更容易看出模式。',
  'analytics.yearDescription': '逐月比較兩個年份。',
}

function readLanguage(): Language {
  return localStorage.getItem(LANGUAGE_KEY) === 'zh' ? 'zh' : 'en'
}

export function useLanguage() {
  const [language, setLanguageState] = useState<Language>(readLanguage)

  useEffect(() => {
    const sync = () => setLanguageState(readLanguage())
    window.addEventListener('storage', sync)
    window.addEventListener(LANGUAGE_CHANGE_EVENT, sync)
    return () => {
      window.removeEventListener('storage', sync)
      window.removeEventListener(LANGUAGE_CHANGE_EVENT, sync)
    }
  }, [])

  const setLanguage = (next: Language) => {
    localStorage.setItem(LANGUAGE_KEY, next)
    setLanguageState(next)
    window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT))
  }

  const t = useMemo(() => (key: string, fallback: string) => language === 'zh' ? (zh[key] || fallback) : fallback, [language])

  return { language, setLanguage, t }
}
